# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTZK5bbWGSrdqw1TIiqrpNVI5VwqXgd_
"""

class Calculator:
    def __init__(self):
        pass

    def calculate(self, expression):
        try:
            return eval(expression)
        except Exception as e:
            return f"Error: {e}"

    def run(self):
        expression = input("Enter a mathematical expression: ")
        result = self.calculate(expression)
        print("Result:", result)
calculator = Calculator()
calculator.run()